/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.istio.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSettingDistribute
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-12-20T14:22:47.686Z[Etc/UTC]")
public class V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSettingDistribute {
  public static final String SERIALIZED_NAME_FROM = "from";
  @SerializedName(SERIALIZED_NAME_FROM)
  private String from;

  public static final String SERIALIZED_NAME_TO = "to";
  @SerializedName(SERIALIZED_NAME_TO)
  private Map<String, Integer> to = null;


  public V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSettingDistribute from(String from) {
    
    this.from = from;
    return this;
  }

   /**
   * Originating locality, &#39;/&#39; separated, e.g.
   * @return from
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Originating locality, '/' separated, e.g.")

  public String getFrom() {
    return from;
  }


  public void setFrom(String from) {
    this.from = from;
  }


  public V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSettingDistribute to(Map<String, Integer> to) {
    
    this.to = to;
    return this;
  }

  public V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSettingDistribute putToItem(String key, Integer toItem) {
    if (this.to == null) {
      this.to = new HashMap<>();
    }
    this.to.put(key, toItem);
    return this;
  }

   /**
   * Map of upstream localities to traffic distribution weights.
   * @return to
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Map of upstream localities to traffic distribution weights.")

  public Map<String, Integer> getTo() {
    return to;
  }


  public void setTo(Map<String, Integer> to) {
    this.to = to;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSettingDistribute v1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSettingDistribute = (V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSettingDistribute) o;
    return Objects.equals(this.from, v1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSettingDistribute.from) &&
        Objects.equals(this.to, v1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSettingDistribute.to);
  }

  @Override
  public int hashCode() {
    return Objects.hash(from, to);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSettingDistribute {\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

