/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.istio.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.istio.models.V1alpha3DestinationRuleSpecTrafficPolicyConnectionPoolHttp;
import io.istio.models.V1alpha3DestinationRuleSpecTrafficPolicyConnectionPoolTcp;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1alpha3DestinationRuleSpecTrafficPolicyConnectionPool
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-12-20T14:22:47.686Z[Etc/UTC]")
public class V1alpha3DestinationRuleSpecTrafficPolicyConnectionPool {
  public static final String SERIALIZED_NAME_HTTP = "http";
  @SerializedName(SERIALIZED_NAME_HTTP)
  private V1alpha3DestinationRuleSpecTrafficPolicyConnectionPoolHttp http;

  public static final String SERIALIZED_NAME_TCP = "tcp";
  @SerializedName(SERIALIZED_NAME_TCP)
  private V1alpha3DestinationRuleSpecTrafficPolicyConnectionPoolTcp tcp;


  public V1alpha3DestinationRuleSpecTrafficPolicyConnectionPool http(V1alpha3DestinationRuleSpecTrafficPolicyConnectionPoolHttp http) {
    
    this.http = http;
    return this;
  }

   /**
   * Get http
   * @return http
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3DestinationRuleSpecTrafficPolicyConnectionPoolHttp getHttp() {
    return http;
  }


  public void setHttp(V1alpha3DestinationRuleSpecTrafficPolicyConnectionPoolHttp http) {
    this.http = http;
  }


  public V1alpha3DestinationRuleSpecTrafficPolicyConnectionPool tcp(V1alpha3DestinationRuleSpecTrafficPolicyConnectionPoolTcp tcp) {
    
    this.tcp = tcp;
    return this;
  }

   /**
   * Get tcp
   * @return tcp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3DestinationRuleSpecTrafficPolicyConnectionPoolTcp getTcp() {
    return tcp;
  }


  public void setTcp(V1alpha3DestinationRuleSpecTrafficPolicyConnectionPoolTcp tcp) {
    this.tcp = tcp;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha3DestinationRuleSpecTrafficPolicyConnectionPool v1alpha3DestinationRuleSpecTrafficPolicyConnectionPool = (V1alpha3DestinationRuleSpecTrafficPolicyConnectionPool) o;
    return Objects.equals(this.http, v1alpha3DestinationRuleSpecTrafficPolicyConnectionPool.http) &&
        Objects.equals(this.tcp, v1alpha3DestinationRuleSpecTrafficPolicyConnectionPool.tcp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(http, tcp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha3DestinationRuleSpecTrafficPolicyConnectionPool {\n");
    sb.append("    http: ").append(toIndentedString(http)).append("\n");
    sb.append("    tcp: ").append(toIndentedString(tcp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

