/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.istio.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.istio.models.V1alpha3DestinationRuleSpecSubsets;
import io.istio.models.V1alpha3DestinationRuleSpecTrafficPolicy1;
import io.istio.models.V1alpha3DestinationRuleSpecWorkloadSelector;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Configuration affecting load balancing, outlier detection, etc. See more details at: https://istio.io/docs/reference/config/networking/destination-rule.html
 */
@ApiModel(description = "Configuration affecting load balancing, outlier detection, etc. See more details at: https://istio.io/docs/reference/config/networking/destination-rule.html")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-12-20T14:22:47.686Z[Etc/UTC]")
public class V1alpha3DestinationRuleSpec {
  public static final String SERIALIZED_NAME_EXPORT_TO = "exportTo";
  @SerializedName(SERIALIZED_NAME_EXPORT_TO)
  private List<String> exportTo = null;

  public static final String SERIALIZED_NAME_HOST = "host";
  @SerializedName(SERIALIZED_NAME_HOST)
  private String host;

  public static final String SERIALIZED_NAME_SUBSETS = "subsets";
  @SerializedName(SERIALIZED_NAME_SUBSETS)
  private List<V1alpha3DestinationRuleSpecSubsets> subsets = null;

  public static final String SERIALIZED_NAME_TRAFFIC_POLICY = "trafficPolicy";
  @SerializedName(SERIALIZED_NAME_TRAFFIC_POLICY)
  private V1alpha3DestinationRuleSpecTrafficPolicy1 trafficPolicy;

  public static final String SERIALIZED_NAME_WORKLOAD_SELECTOR = "workloadSelector";
  @SerializedName(SERIALIZED_NAME_WORKLOAD_SELECTOR)
  private V1alpha3DestinationRuleSpecWorkloadSelector workloadSelector;


  public V1alpha3DestinationRuleSpec exportTo(List<String> exportTo) {
    
    this.exportTo = exportTo;
    return this;
  }

  public V1alpha3DestinationRuleSpec addExportToItem(String exportToItem) {
    if (this.exportTo == null) {
      this.exportTo = new ArrayList<>();
    }
    this.exportTo.add(exportToItem);
    return this;
  }

   /**
   * A list of namespaces to which this destination rule is exported.
   * @return exportTo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of namespaces to which this destination rule is exported.")

  public List<String> getExportTo() {
    return exportTo;
  }


  public void setExportTo(List<String> exportTo) {
    this.exportTo = exportTo;
  }


  public V1alpha3DestinationRuleSpec host(String host) {
    
    this.host = host;
    return this;
  }

   /**
   * The name of a service from the service registry.
   * @return host
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of a service from the service registry.")

  public String getHost() {
    return host;
  }


  public void setHost(String host) {
    this.host = host;
  }


  public V1alpha3DestinationRuleSpec subsets(List<V1alpha3DestinationRuleSpecSubsets> subsets) {
    
    this.subsets = subsets;
    return this;
  }

  public V1alpha3DestinationRuleSpec addSubsetsItem(V1alpha3DestinationRuleSpecSubsets subsetsItem) {
    if (this.subsets == null) {
      this.subsets = new ArrayList<>();
    }
    this.subsets.add(subsetsItem);
    return this;
  }

   /**
   * Get subsets
   * @return subsets
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1alpha3DestinationRuleSpecSubsets> getSubsets() {
    return subsets;
  }


  public void setSubsets(List<V1alpha3DestinationRuleSpecSubsets> subsets) {
    this.subsets = subsets;
  }


  public V1alpha3DestinationRuleSpec trafficPolicy(V1alpha3DestinationRuleSpecTrafficPolicy1 trafficPolicy) {
    
    this.trafficPolicy = trafficPolicy;
    return this;
  }

   /**
   * Get trafficPolicy
   * @return trafficPolicy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3DestinationRuleSpecTrafficPolicy1 getTrafficPolicy() {
    return trafficPolicy;
  }


  public void setTrafficPolicy(V1alpha3DestinationRuleSpecTrafficPolicy1 trafficPolicy) {
    this.trafficPolicy = trafficPolicy;
  }


  public V1alpha3DestinationRuleSpec workloadSelector(V1alpha3DestinationRuleSpecWorkloadSelector workloadSelector) {
    
    this.workloadSelector = workloadSelector;
    return this;
  }

   /**
   * Get workloadSelector
   * @return workloadSelector
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3DestinationRuleSpecWorkloadSelector getWorkloadSelector() {
    return workloadSelector;
  }


  public void setWorkloadSelector(V1alpha3DestinationRuleSpecWorkloadSelector workloadSelector) {
    this.workloadSelector = workloadSelector;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha3DestinationRuleSpec v1alpha3DestinationRuleSpec = (V1alpha3DestinationRuleSpec) o;
    return Objects.equals(this.exportTo, v1alpha3DestinationRuleSpec.exportTo) &&
        Objects.equals(this.host, v1alpha3DestinationRuleSpec.host) &&
        Objects.equals(this.subsets, v1alpha3DestinationRuleSpec.subsets) &&
        Objects.equals(this.trafficPolicy, v1alpha3DestinationRuleSpec.trafficPolicy) &&
        Objects.equals(this.workloadSelector, v1alpha3DestinationRuleSpec.workloadSelector);
  }

  @Override
  public int hashCode() {
    return Objects.hash(exportTo, host, subsets, trafficPolicy, workloadSelector);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha3DestinationRuleSpec {\n");
    sb.append("    exportTo: ").append(toIndentedString(exportTo)).append("\n");
    sb.append("    host: ").append(toIndentedString(host)).append("\n");
    sb.append("    subsets: ").append(toIndentedString(subsets)).append("\n");
    sb.append("    trafficPolicy: ").append(toIndentedString(trafficPolicy)).append("\n");
    sb.append("    workloadSelector: ").append(toIndentedString(workloadSelector)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

