/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.istio.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.istio.models.V1alpha3DestinationRuleSpecTrafficPolicy;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * V1alpha3DestinationRuleSpecSubsets
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-12-20T14:22:47.686Z[Etc/UTC]")
public class V1alpha3DestinationRuleSpecSubsets {
  public static final String SERIALIZED_NAME_LABELS = "labels";
  @SerializedName(SERIALIZED_NAME_LABELS)
  private Map<String, String> labels = null;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_TRAFFIC_POLICY = "trafficPolicy";
  @SerializedName(SERIALIZED_NAME_TRAFFIC_POLICY)
  private V1alpha3DestinationRuleSpecTrafficPolicy trafficPolicy;


  public V1alpha3DestinationRuleSpecSubsets labels(Map<String, String> labels) {
    
    this.labels = labels;
    return this;
  }

  public V1alpha3DestinationRuleSpecSubsets putLabelsItem(String key, String labelsItem) {
    if (this.labels == null) {
      this.labels = new HashMap<>();
    }
    this.labels.put(key, labelsItem);
    return this;
  }

   /**
   * Get labels
   * @return labels
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Map<String, String> getLabels() {
    return labels;
  }


  public void setLabels(Map<String, String> labels) {
    this.labels = labels;
  }


  public V1alpha3DestinationRuleSpecSubsets name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Name of the subset.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Name of the subset.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public V1alpha3DestinationRuleSpecSubsets trafficPolicy(V1alpha3DestinationRuleSpecTrafficPolicy trafficPolicy) {
    
    this.trafficPolicy = trafficPolicy;
    return this;
  }

   /**
   * Get trafficPolicy
   * @return trafficPolicy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3DestinationRuleSpecTrafficPolicy getTrafficPolicy() {
    return trafficPolicy;
  }


  public void setTrafficPolicy(V1alpha3DestinationRuleSpecTrafficPolicy trafficPolicy) {
    this.trafficPolicy = trafficPolicy;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha3DestinationRuleSpecSubsets v1alpha3DestinationRuleSpecSubsets = (V1alpha3DestinationRuleSpecSubsets) o;
    return Objects.equals(this.labels, v1alpha3DestinationRuleSpecSubsets.labels) &&
        Objects.equals(this.name, v1alpha3DestinationRuleSpecSubsets.name) &&
        Objects.equals(this.trafficPolicy, v1alpha3DestinationRuleSpecSubsets.trafficPolicy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(labels, name, trafficPolicy);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha3DestinationRuleSpecSubsets {\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    trafficPolicy: ").append(toIndentedString(trafficPolicy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

