/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.istio.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * The ring/modulo hash load balancer implements consistent hashing to backend hosts.
 */
@ApiModel(description = "The ring/modulo hash load balancer implements consistent hashing to backend hosts.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-12-20T14:22:47.686Z[Etc/UTC]")
public class V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHashRingHash {
  public static final String SERIALIZED_NAME_MINIMUM_RING_SIZE = "minimumRingSize";
  @SerializedName(SERIALIZED_NAME_MINIMUM_RING_SIZE)
  private Integer minimumRingSize;


  public V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHashRingHash minimumRingSize(Integer minimumRingSize) {
    
    this.minimumRingSize = minimumRingSize;
    return this;
  }

   /**
   * Get minimumRingSize
   * @return minimumRingSize
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getMinimumRingSize() {
    return minimumRingSize;
  }


  public void setMinimumRingSize(Integer minimumRingSize) {
    this.minimumRingSize = minimumRingSize;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHashRingHash v1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHashRingHash = (V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHashRingHash) o;
    return Objects.equals(this.minimumRingSize, v1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHashRingHash.minimumRingSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(minimumRingSize);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHashRingHash {\n");
    sb.append("    minimumRingSize: ").append(toIndentedString(minimumRingSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

