/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.istio.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.istio.models.V1alpha3DestinationRuleSpecTrafficPolicyConnectionPool;
import io.istio.models.V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancer;
import io.istio.models.V1alpha3DestinationRuleSpecTrafficPolicyOutlierDetection;
import io.istio.models.V1alpha3DestinationRuleSpecTrafficPolicyPort;
import io.istio.models.V1alpha3DestinationRuleSpecTrafficPolicyTls;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1alpha3DestinationRuleSpecTrafficPolicyPortLevelSettings
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-12-20T14:22:47.686Z[Etc/UTC]")
public class V1alpha3DestinationRuleSpecTrafficPolicyPortLevelSettings {
  public static final String SERIALIZED_NAME_CONNECTION_POOL = "connectionPool";
  @SerializedName(SERIALIZED_NAME_CONNECTION_POOL)
  private V1alpha3DestinationRuleSpecTrafficPolicyConnectionPool connectionPool;

  public static final String SERIALIZED_NAME_LOAD_BALANCER = "loadBalancer";
  @SerializedName(SERIALIZED_NAME_LOAD_BALANCER)
  private V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancer loadBalancer;

  public static final String SERIALIZED_NAME_OUTLIER_DETECTION = "outlierDetection";
  @SerializedName(SERIALIZED_NAME_OUTLIER_DETECTION)
  private V1alpha3DestinationRuleSpecTrafficPolicyOutlierDetection outlierDetection;

  public static final String SERIALIZED_NAME_PORT = "port";
  @SerializedName(SERIALIZED_NAME_PORT)
  private V1alpha3DestinationRuleSpecTrafficPolicyPort port;

  public static final String SERIALIZED_NAME_TLS = "tls";
  @SerializedName(SERIALIZED_NAME_TLS)
  private V1alpha3DestinationRuleSpecTrafficPolicyTls tls;


  public V1alpha3DestinationRuleSpecTrafficPolicyPortLevelSettings connectionPool(V1alpha3DestinationRuleSpecTrafficPolicyConnectionPool connectionPool) {
    
    this.connectionPool = connectionPool;
    return this;
  }

   /**
   * Get connectionPool
   * @return connectionPool
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3DestinationRuleSpecTrafficPolicyConnectionPool getConnectionPool() {
    return connectionPool;
  }


  public void setConnectionPool(V1alpha3DestinationRuleSpecTrafficPolicyConnectionPool connectionPool) {
    this.connectionPool = connectionPool;
  }


  public V1alpha3DestinationRuleSpecTrafficPolicyPortLevelSettings loadBalancer(V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancer loadBalancer) {
    
    this.loadBalancer = loadBalancer;
    return this;
  }

   /**
   * Get loadBalancer
   * @return loadBalancer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancer getLoadBalancer() {
    return loadBalancer;
  }


  public void setLoadBalancer(V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancer loadBalancer) {
    this.loadBalancer = loadBalancer;
  }


  public V1alpha3DestinationRuleSpecTrafficPolicyPortLevelSettings outlierDetection(V1alpha3DestinationRuleSpecTrafficPolicyOutlierDetection outlierDetection) {
    
    this.outlierDetection = outlierDetection;
    return this;
  }

   /**
   * Get outlierDetection
   * @return outlierDetection
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3DestinationRuleSpecTrafficPolicyOutlierDetection getOutlierDetection() {
    return outlierDetection;
  }


  public void setOutlierDetection(V1alpha3DestinationRuleSpecTrafficPolicyOutlierDetection outlierDetection) {
    this.outlierDetection = outlierDetection;
  }


  public V1alpha3DestinationRuleSpecTrafficPolicyPortLevelSettings port(V1alpha3DestinationRuleSpecTrafficPolicyPort port) {
    
    this.port = port;
    return this;
  }

   /**
   * Get port
   * @return port
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3DestinationRuleSpecTrafficPolicyPort getPort() {
    return port;
  }


  public void setPort(V1alpha3DestinationRuleSpecTrafficPolicyPort port) {
    this.port = port;
  }


  public V1alpha3DestinationRuleSpecTrafficPolicyPortLevelSettings tls(V1alpha3DestinationRuleSpecTrafficPolicyTls tls) {
    
    this.tls = tls;
    return this;
  }

   /**
   * Get tls
   * @return tls
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3DestinationRuleSpecTrafficPolicyTls getTls() {
    return tls;
  }


  public void setTls(V1alpha3DestinationRuleSpecTrafficPolicyTls tls) {
    this.tls = tls;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha3DestinationRuleSpecTrafficPolicyPortLevelSettings v1alpha3DestinationRuleSpecTrafficPolicyPortLevelSettings = (V1alpha3DestinationRuleSpecTrafficPolicyPortLevelSettings) o;
    return Objects.equals(this.connectionPool, v1alpha3DestinationRuleSpecTrafficPolicyPortLevelSettings.connectionPool) &&
        Objects.equals(this.loadBalancer, v1alpha3DestinationRuleSpecTrafficPolicyPortLevelSettings.loadBalancer) &&
        Objects.equals(this.outlierDetection, v1alpha3DestinationRuleSpecTrafficPolicyPortLevelSettings.outlierDetection) &&
        Objects.equals(this.port, v1alpha3DestinationRuleSpecTrafficPolicyPortLevelSettings.port) &&
        Objects.equals(this.tls, v1alpha3DestinationRuleSpecTrafficPolicyPortLevelSettings.tls);
  }

  @Override
  public int hashCode() {
    return Objects.hash(connectionPool, loadBalancer, outlierDetection, port, tls);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha3DestinationRuleSpecTrafficPolicyPortLevelSettings {\n");
    sb.append("    connectionPool: ").append(toIndentedString(connectionPool)).append("\n");
    sb.append("    loadBalancer: ").append(toIndentedString(loadBalancer)).append("\n");
    sb.append("    outlierDetection: ").append(toIndentedString(outlierDetection)).append("\n");
    sb.append("    port: ").append(toIndentedString(port)).append("\n");
    sb.append("    tls: ").append(toIndentedString(tls)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

