/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.istio.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.istio.models.V1alpha1WasmPluginSpecVmConfigEnv;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Configuration for a Wasm VM.
 */
@ApiModel(description = "Configuration for a Wasm VM.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-12-20T14:22:47.686Z[Etc/UTC]")
public class V1alpha1WasmPluginSpecVmConfig {
  public static final String SERIALIZED_NAME_ENV = "env";
  @SerializedName(SERIALIZED_NAME_ENV)
  private List<V1alpha1WasmPluginSpecVmConfigEnv> env = null;


  public V1alpha1WasmPluginSpecVmConfig env(List<V1alpha1WasmPluginSpecVmConfigEnv> env) {
    
    this.env = env;
    return this;
  }

  public V1alpha1WasmPluginSpecVmConfig addEnvItem(V1alpha1WasmPluginSpecVmConfigEnv envItem) {
    if (this.env == null) {
      this.env = new ArrayList<>();
    }
    this.env.add(envItem);
    return this;
  }

   /**
   * Specifies environment variables to be injected to this VM.
   * @return env
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Specifies environment variables to be injected to this VM.")

  public List<V1alpha1WasmPluginSpecVmConfigEnv> getEnv() {
    return env;
  }


  public void setEnv(List<V1alpha1WasmPluginSpecVmConfigEnv> env) {
    this.env = env;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1WasmPluginSpecVmConfig v1alpha1WasmPluginSpecVmConfig = (V1alpha1WasmPluginSpecVmConfig) o;
    return Objects.equals(this.env, v1alpha1WasmPluginSpecVmConfig.env);
  }

  @Override
  public int hashCode() {
    return Objects.hash(env);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1WasmPluginSpecVmConfig {\n");
    sb.append("    env: ").append(toIndentedString(env)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

