/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.istio.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.istio.models.V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSettingDistribute;
import io.istio.models.V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSettingFailover;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSetting
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-12-20T14:22:47.686Z[Etc/UTC]")
public class V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSetting {
  public static final String SERIALIZED_NAME_DISTRIBUTE = "distribute";
  @SerializedName(SERIALIZED_NAME_DISTRIBUTE)
  private List<V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSettingDistribute> distribute = null;

  public static final String SERIALIZED_NAME_ENABLED = "enabled";
  @SerializedName(SERIALIZED_NAME_ENABLED)
  private Object enabled;

  public static final String SERIALIZED_NAME_FAILOVER = "failover";
  @SerializedName(SERIALIZED_NAME_FAILOVER)
  private List<V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSettingFailover> failover = null;

  public static final String SERIALIZED_NAME_FAILOVER_PRIORITY = "failoverPriority";
  @SerializedName(SERIALIZED_NAME_FAILOVER_PRIORITY)
  private List<String> failoverPriority = null;


  public V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSetting distribute(List<V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSettingDistribute> distribute) {
    
    this.distribute = distribute;
    return this;
  }

  public V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSetting addDistributeItem(V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSettingDistribute distributeItem) {
    if (this.distribute == null) {
      this.distribute = new ArrayList<>();
    }
    this.distribute.add(distributeItem);
    return this;
  }

   /**
   * Optional: only one of distribute, failover or failoverPriority can be set.
   * @return distribute
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Optional: only one of distribute, failover or failoverPriority can be set.")

  public List<V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSettingDistribute> getDistribute() {
    return distribute;
  }


  public void setDistribute(List<V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSettingDistribute> distribute) {
    this.distribute = distribute;
  }


  public V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSetting enabled(Object enabled) {
    
    this.enabled = enabled;
    return this;
  }

   /**
   * enable locality load balancing, this is DestinationRule-level and will override mesh wide settings in entirety.
   * @return enabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "enable locality load balancing, this is DestinationRule-level and will override mesh wide settings in entirety.")

  public Object getEnabled() {
    return enabled;
  }


  public void setEnabled(Object enabled) {
    this.enabled = enabled;
  }


  public V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSetting failover(List<V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSettingFailover> failover) {
    
    this.failover = failover;
    return this;
  }

  public V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSetting addFailoverItem(V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSettingFailover failoverItem) {
    if (this.failover == null) {
      this.failover = new ArrayList<>();
    }
    this.failover.add(failoverItem);
    return this;
  }

   /**
   * Optional: only one of distribute, failover or failoverPriority can be set.
   * @return failover
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Optional: only one of distribute, failover or failoverPriority can be set.")

  public List<V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSettingFailover> getFailover() {
    return failover;
  }


  public void setFailover(List<V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSettingFailover> failover) {
    this.failover = failover;
  }


  public V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSetting failoverPriority(List<String> failoverPriority) {
    
    this.failoverPriority = failoverPriority;
    return this;
  }

  public V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSetting addFailoverPriorityItem(String failoverPriorityItem) {
    if (this.failoverPriority == null) {
      this.failoverPriority = new ArrayList<>();
    }
    this.failoverPriority.add(failoverPriorityItem);
    return this;
  }

   /**
   * failoverPriority is an ordered list of labels used to sort endpoints to do priority based load balancing.
   * @return failoverPriority
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "failoverPriority is an ordered list of labels used to sort endpoints to do priority based load balancing.")

  public List<String> getFailoverPriority() {
    return failoverPriority;
  }


  public void setFailoverPriority(List<String> failoverPriority) {
    this.failoverPriority = failoverPriority;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSetting v1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSetting = (V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSetting) o;
    return Objects.equals(this.distribute, v1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSetting.distribute) &&
        Objects.equals(this.enabled, v1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSetting.enabled) &&
        Objects.equals(this.failover, v1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSetting.failover) &&
        Objects.equals(this.failoverPriority, v1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSetting.failoverPriority);
  }

  @Override
  public int hashCode() {
    return Objects.hash(distribute, enabled, failover, failoverPriority);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSetting {\n");
    sb.append("    distribute: ").append(toIndentedString(distribute)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    failover: ").append(toIndentedString(failover)).append("\n");
    sb.append("    failoverPriority: ").append(toIndentedString(failoverPriority)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

