/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.istio.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.istio.models.V1alpha3DestinationRuleSpecTrafficPolicyConnectionPool;
import io.istio.models.V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancer;
import io.istio.models.V1alpha3DestinationRuleSpecTrafficPolicyOutlierDetection;
import io.istio.models.V1alpha3DestinationRuleSpecTrafficPolicyPortLevelSettings;
import io.istio.models.V1alpha3DestinationRuleSpecTrafficPolicyTls;
import io.istio.models.V1alpha3DestinationRuleSpecTrafficPolicyTunnel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1alpha3DestinationRuleSpecTrafficPolicy1
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-12-20T14:22:47.686Z[Etc/UTC]")
public class V1alpha3DestinationRuleSpecTrafficPolicy1 {
  public static final String SERIALIZED_NAME_CONNECTION_POOL = "connectionPool";
  @SerializedName(SERIALIZED_NAME_CONNECTION_POOL)
  private V1alpha3DestinationRuleSpecTrafficPolicyConnectionPool connectionPool;

  public static final String SERIALIZED_NAME_LOAD_BALANCER = "loadBalancer";
  @SerializedName(SERIALIZED_NAME_LOAD_BALANCER)
  private V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancer loadBalancer;

  public static final String SERIALIZED_NAME_OUTLIER_DETECTION = "outlierDetection";
  @SerializedName(SERIALIZED_NAME_OUTLIER_DETECTION)
  private V1alpha3DestinationRuleSpecTrafficPolicyOutlierDetection outlierDetection;

  public static final String SERIALIZED_NAME_PORT_LEVEL_SETTINGS = "portLevelSettings";
  @SerializedName(SERIALIZED_NAME_PORT_LEVEL_SETTINGS)
  private List<V1alpha3DestinationRuleSpecTrafficPolicyPortLevelSettings> portLevelSettings = null;

  public static final String SERIALIZED_NAME_TLS = "tls";
  @SerializedName(SERIALIZED_NAME_TLS)
  private V1alpha3DestinationRuleSpecTrafficPolicyTls tls;

  public static final String SERIALIZED_NAME_TUNNEL = "tunnel";
  @SerializedName(SERIALIZED_NAME_TUNNEL)
  private V1alpha3DestinationRuleSpecTrafficPolicyTunnel tunnel;


  public V1alpha3DestinationRuleSpecTrafficPolicy1 connectionPool(V1alpha3DestinationRuleSpecTrafficPolicyConnectionPool connectionPool) {
    
    this.connectionPool = connectionPool;
    return this;
  }

   /**
   * Get connectionPool
   * @return connectionPool
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3DestinationRuleSpecTrafficPolicyConnectionPool getConnectionPool() {
    return connectionPool;
  }


  public void setConnectionPool(V1alpha3DestinationRuleSpecTrafficPolicyConnectionPool connectionPool) {
    this.connectionPool = connectionPool;
  }


  public V1alpha3DestinationRuleSpecTrafficPolicy1 loadBalancer(V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancer loadBalancer) {
    
    this.loadBalancer = loadBalancer;
    return this;
  }

   /**
   * Get loadBalancer
   * @return loadBalancer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancer getLoadBalancer() {
    return loadBalancer;
  }


  public void setLoadBalancer(V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancer loadBalancer) {
    this.loadBalancer = loadBalancer;
  }


  public V1alpha3DestinationRuleSpecTrafficPolicy1 outlierDetection(V1alpha3DestinationRuleSpecTrafficPolicyOutlierDetection outlierDetection) {
    
    this.outlierDetection = outlierDetection;
    return this;
  }

   /**
   * Get outlierDetection
   * @return outlierDetection
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3DestinationRuleSpecTrafficPolicyOutlierDetection getOutlierDetection() {
    return outlierDetection;
  }


  public void setOutlierDetection(V1alpha3DestinationRuleSpecTrafficPolicyOutlierDetection outlierDetection) {
    this.outlierDetection = outlierDetection;
  }


  public V1alpha3DestinationRuleSpecTrafficPolicy1 portLevelSettings(List<V1alpha3DestinationRuleSpecTrafficPolicyPortLevelSettings> portLevelSettings) {
    
    this.portLevelSettings = portLevelSettings;
    return this;
  }

  public V1alpha3DestinationRuleSpecTrafficPolicy1 addPortLevelSettingsItem(V1alpha3DestinationRuleSpecTrafficPolicyPortLevelSettings portLevelSettingsItem) {
    if (this.portLevelSettings == null) {
      this.portLevelSettings = new ArrayList<>();
    }
    this.portLevelSettings.add(portLevelSettingsItem);
    return this;
  }

   /**
   * Traffic policies specific to individual ports.
   * @return portLevelSettings
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Traffic policies specific to individual ports.")

  public List<V1alpha3DestinationRuleSpecTrafficPolicyPortLevelSettings> getPortLevelSettings() {
    return portLevelSettings;
  }


  public void setPortLevelSettings(List<V1alpha3DestinationRuleSpecTrafficPolicyPortLevelSettings> portLevelSettings) {
    this.portLevelSettings = portLevelSettings;
  }


  public V1alpha3DestinationRuleSpecTrafficPolicy1 tls(V1alpha3DestinationRuleSpecTrafficPolicyTls tls) {
    
    this.tls = tls;
    return this;
  }

   /**
   * Get tls
   * @return tls
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3DestinationRuleSpecTrafficPolicyTls getTls() {
    return tls;
  }


  public void setTls(V1alpha3DestinationRuleSpecTrafficPolicyTls tls) {
    this.tls = tls;
  }


  public V1alpha3DestinationRuleSpecTrafficPolicy1 tunnel(V1alpha3DestinationRuleSpecTrafficPolicyTunnel tunnel) {
    
    this.tunnel = tunnel;
    return this;
  }

   /**
   * Get tunnel
   * @return tunnel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3DestinationRuleSpecTrafficPolicyTunnel getTunnel() {
    return tunnel;
  }


  public void setTunnel(V1alpha3DestinationRuleSpecTrafficPolicyTunnel tunnel) {
    this.tunnel = tunnel;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha3DestinationRuleSpecTrafficPolicy1 v1alpha3DestinationRuleSpecTrafficPolicy1 = (V1alpha3DestinationRuleSpecTrafficPolicy1) o;
    return Objects.equals(this.connectionPool, v1alpha3DestinationRuleSpecTrafficPolicy1.connectionPool) &&
        Objects.equals(this.loadBalancer, v1alpha3DestinationRuleSpecTrafficPolicy1.loadBalancer) &&
        Objects.equals(this.outlierDetection, v1alpha3DestinationRuleSpecTrafficPolicy1.outlierDetection) &&
        Objects.equals(this.portLevelSettings, v1alpha3DestinationRuleSpecTrafficPolicy1.portLevelSettings) &&
        Objects.equals(this.tls, v1alpha3DestinationRuleSpecTrafficPolicy1.tls) &&
        Objects.equals(this.tunnel, v1alpha3DestinationRuleSpecTrafficPolicy1.tunnel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(connectionPool, loadBalancer, outlierDetection, portLevelSettings, tls, tunnel);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha3DestinationRuleSpecTrafficPolicy1 {\n");
    sb.append("    connectionPool: ").append(toIndentedString(connectionPool)).append("\n");
    sb.append("    loadBalancer: ").append(toIndentedString(loadBalancer)).append("\n");
    sb.append("    outlierDetection: ").append(toIndentedString(outlierDetection)).append("\n");
    sb.append("    portLevelSettings: ").append(toIndentedString(portLevelSettings)).append("\n");
    sb.append("    tls: ").append(toIndentedString(tls)).append("\n");
    sb.append("    tunnel: ").append(toIndentedString(tunnel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

