/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.istio.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * TLS related settings for connections to the upstream service.
 */
@ApiModel(description = "TLS related settings for connections to the upstream service.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-12-20T14:22:47.686Z[Etc/UTC]")
public class V1alpha3DestinationRuleSpecTrafficPolicyTls {
  public static final String SERIALIZED_NAME_CA_CERTIFICATES = "caCertificates";
  @SerializedName(SERIALIZED_NAME_CA_CERTIFICATES)
  private String caCertificates;

  public static final String SERIALIZED_NAME_CLIENT_CERTIFICATE = "clientCertificate";
  @SerializedName(SERIALIZED_NAME_CLIENT_CERTIFICATE)
  private String clientCertificate;

  public static final String SERIALIZED_NAME_CREDENTIAL_NAME = "credentialName";
  @SerializedName(SERIALIZED_NAME_CREDENTIAL_NAME)
  private String credentialName;

  public static final String SERIALIZED_NAME_INSECURE_SKIP_VERIFY = "insecureSkipVerify";
  @SerializedName(SERIALIZED_NAME_INSECURE_SKIP_VERIFY)
  private Object insecureSkipVerify;

  /**
   * Gets or Sets mode
   */
  @JsonAdapter(ModeEnum.Adapter.class)
  public enum ModeEnum {
    DISABLE("DISABLE"),
    
    SIMPLE("SIMPLE"),
    
    MUTUAL("MUTUAL"),
    
    ISTIO_MUTUAL("ISTIO_MUTUAL");

    private String value;

    ModeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ModeEnum fromValue(String value) {
      for (ModeEnum b : ModeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ModeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ModeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ModeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ModeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_MODE = "mode";
  @SerializedName(SERIALIZED_NAME_MODE)
  private ModeEnum mode;

  public static final String SERIALIZED_NAME_PRIVATE_KEY = "privateKey";
  @SerializedName(SERIALIZED_NAME_PRIVATE_KEY)
  private String privateKey;

  public static final String SERIALIZED_NAME_SNI = "sni";
  @SerializedName(SERIALIZED_NAME_SNI)
  private String sni;

  public static final String SERIALIZED_NAME_SUBJECT_ALT_NAMES = "subjectAltNames";
  @SerializedName(SERIALIZED_NAME_SUBJECT_ALT_NAMES)
  private List<String> subjectAltNames = null;


  public V1alpha3DestinationRuleSpecTrafficPolicyTls caCertificates(String caCertificates) {
    
    this.caCertificates = caCertificates;
    return this;
  }

   /**
   * Get caCertificates
   * @return caCertificates
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCaCertificates() {
    return caCertificates;
  }


  public void setCaCertificates(String caCertificates) {
    this.caCertificates = caCertificates;
  }


  public V1alpha3DestinationRuleSpecTrafficPolicyTls clientCertificate(String clientCertificate) {
    
    this.clientCertificate = clientCertificate;
    return this;
  }

   /**
   * REQUIRED if mode is &#x60;MUTUAL&#x60;.
   * @return clientCertificate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "REQUIRED if mode is `MUTUAL`.")

  public String getClientCertificate() {
    return clientCertificate;
  }


  public void setClientCertificate(String clientCertificate) {
    this.clientCertificate = clientCertificate;
  }


  public V1alpha3DestinationRuleSpecTrafficPolicyTls credentialName(String credentialName) {
    
    this.credentialName = credentialName;
    return this;
  }

   /**
   * Get credentialName
   * @return credentialName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCredentialName() {
    return credentialName;
  }


  public void setCredentialName(String credentialName) {
    this.credentialName = credentialName;
  }


  public V1alpha3DestinationRuleSpecTrafficPolicyTls insecureSkipVerify(Object insecureSkipVerify) {
    
    this.insecureSkipVerify = insecureSkipVerify;
    return this;
  }

   /**
   * Get insecureSkipVerify
   * @return insecureSkipVerify
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getInsecureSkipVerify() {
    return insecureSkipVerify;
  }


  public void setInsecureSkipVerify(Object insecureSkipVerify) {
    this.insecureSkipVerify = insecureSkipVerify;
  }


  public V1alpha3DestinationRuleSpecTrafficPolicyTls mode(ModeEnum mode) {
    
    this.mode = mode;
    return this;
  }

   /**
   * Get mode
   * @return mode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ModeEnum getMode() {
    return mode;
  }


  public void setMode(ModeEnum mode) {
    this.mode = mode;
  }


  public V1alpha3DestinationRuleSpecTrafficPolicyTls privateKey(String privateKey) {
    
    this.privateKey = privateKey;
    return this;
  }

   /**
   * REQUIRED if mode is &#x60;MUTUAL&#x60;.
   * @return privateKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "REQUIRED if mode is `MUTUAL`.")

  public String getPrivateKey() {
    return privateKey;
  }


  public void setPrivateKey(String privateKey) {
    this.privateKey = privateKey;
  }


  public V1alpha3DestinationRuleSpecTrafficPolicyTls sni(String sni) {
    
    this.sni = sni;
    return this;
  }

   /**
   * SNI string to present to the server during TLS handshake.
   * @return sni
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "SNI string to present to the server during TLS handshake.")

  public String getSni() {
    return sni;
  }


  public void setSni(String sni) {
    this.sni = sni;
  }


  public V1alpha3DestinationRuleSpecTrafficPolicyTls subjectAltNames(List<String> subjectAltNames) {
    
    this.subjectAltNames = subjectAltNames;
    return this;
  }

  public V1alpha3DestinationRuleSpecTrafficPolicyTls addSubjectAltNamesItem(String subjectAltNamesItem) {
    if (this.subjectAltNames == null) {
      this.subjectAltNames = new ArrayList<>();
    }
    this.subjectAltNames.add(subjectAltNamesItem);
    return this;
  }

   /**
   * Get subjectAltNames
   * @return subjectAltNames
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getSubjectAltNames() {
    return subjectAltNames;
  }


  public void setSubjectAltNames(List<String> subjectAltNames) {
    this.subjectAltNames = subjectAltNames;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha3DestinationRuleSpecTrafficPolicyTls v1alpha3DestinationRuleSpecTrafficPolicyTls = (V1alpha3DestinationRuleSpecTrafficPolicyTls) o;
    return Objects.equals(this.caCertificates, v1alpha3DestinationRuleSpecTrafficPolicyTls.caCertificates) &&
        Objects.equals(this.clientCertificate, v1alpha3DestinationRuleSpecTrafficPolicyTls.clientCertificate) &&
        Objects.equals(this.credentialName, v1alpha3DestinationRuleSpecTrafficPolicyTls.credentialName) &&
        Objects.equals(this.insecureSkipVerify, v1alpha3DestinationRuleSpecTrafficPolicyTls.insecureSkipVerify) &&
        Objects.equals(this.mode, v1alpha3DestinationRuleSpecTrafficPolicyTls.mode) &&
        Objects.equals(this.privateKey, v1alpha3DestinationRuleSpecTrafficPolicyTls.privateKey) &&
        Objects.equals(this.sni, v1alpha3DestinationRuleSpecTrafficPolicyTls.sni) &&
        Objects.equals(this.subjectAltNames, v1alpha3DestinationRuleSpecTrafficPolicyTls.subjectAltNames);
  }

  @Override
  public int hashCode() {
    return Objects.hash(caCertificates, clientCertificate, credentialName, insecureSkipVerify, mode, privateKey, sni, subjectAltNames);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha3DestinationRuleSpecTrafficPolicyTls {\n");
    sb.append("    caCertificates: ").append(toIndentedString(caCertificates)).append("\n");
    sb.append("    clientCertificate: ").append(toIndentedString(clientCertificate)).append("\n");
    sb.append("    credentialName: ").append(toIndentedString(credentialName)).append("\n");
    sb.append("    insecureSkipVerify: ").append(toIndentedString(insecureSkipVerify)).append("\n");
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("    privateKey: ").append(toIndentedString(privateKey)).append("\n");
    sb.append("    sni: ").append(toIndentedString(sni)).append("\n");
    sb.append("    subjectAltNames: ").append(toIndentedString(subjectAltNames)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

