/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.istio.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.istio.models.V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHash;
import io.istio.models.V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSetting;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Settings controlling the load balancer algorithms.
 */
@ApiModel(description = "Settings controlling the load balancer algorithms.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-12-20T14:22:47.686Z[Etc/UTC]")
public class V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancer {
  public static final String SERIALIZED_NAME_CONSISTENT_HASH = "consistentHash";
  @SerializedName(SERIALIZED_NAME_CONSISTENT_HASH)
  private V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHash consistentHash;

  public static final String SERIALIZED_NAME_LOCALITY_LB_SETTING = "localityLbSetting";
  @SerializedName(SERIALIZED_NAME_LOCALITY_LB_SETTING)
  private V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSetting localityLbSetting;

  /**
   * Gets or Sets simple
   */
  @JsonAdapter(SimpleEnum.Adapter.class)
  public enum SimpleEnum {
    UNSPECIFIED("UNSPECIFIED"),
    
    LEAST_CONN("LEAST_CONN"),
    
    RANDOM("RANDOM"),
    
    PASSTHROUGH("PASSTHROUGH"),
    
    ROUND_ROBIN("ROUND_ROBIN"),
    
    LEAST_REQUEST("LEAST_REQUEST");

    private String value;

    SimpleEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SimpleEnum fromValue(String value) {
      for (SimpleEnum b : SimpleEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<SimpleEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SimpleEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SimpleEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return SimpleEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_SIMPLE = "simple";
  @SerializedName(SERIALIZED_NAME_SIMPLE)
  private SimpleEnum simple;

  public static final String SERIALIZED_NAME_WARMUP_DURATION_SECS = "warmupDurationSecs";
  @SerializedName(SERIALIZED_NAME_WARMUP_DURATION_SECS)
  private String warmupDurationSecs;


  public V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancer consistentHash(V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHash consistentHash) {
    
    this.consistentHash = consistentHash;
    return this;
  }

   /**
   * Get consistentHash
   * @return consistentHash
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHash getConsistentHash() {
    return consistentHash;
  }


  public void setConsistentHash(V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHash consistentHash) {
    this.consistentHash = consistentHash;
  }


  public V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancer localityLbSetting(V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSetting localityLbSetting) {
    
    this.localityLbSetting = localityLbSetting;
    return this;
  }

   /**
   * Get localityLbSetting
   * @return localityLbSetting
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSetting getLocalityLbSetting() {
    return localityLbSetting;
  }


  public void setLocalityLbSetting(V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerLocalityLbSetting localityLbSetting) {
    this.localityLbSetting = localityLbSetting;
  }


  public V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancer simple(SimpleEnum simple) {
    
    this.simple = simple;
    return this;
  }

   /**
   * Get simple
   * @return simple
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public SimpleEnum getSimple() {
    return simple;
  }


  public void setSimple(SimpleEnum simple) {
    this.simple = simple;
  }


  public V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancer warmupDurationSecs(String warmupDurationSecs) {
    
    this.warmupDurationSecs = warmupDurationSecs;
    return this;
  }

   /**
   * Represents the warmup duration of Service.
   * @return warmupDurationSecs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Represents the warmup duration of Service.")

  public String getWarmupDurationSecs() {
    return warmupDurationSecs;
  }


  public void setWarmupDurationSecs(String warmupDurationSecs) {
    this.warmupDurationSecs = warmupDurationSecs;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancer v1alpha3DestinationRuleSpecTrafficPolicyLoadBalancer = (V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancer) o;
    return Objects.equals(this.consistentHash, v1alpha3DestinationRuleSpecTrafficPolicyLoadBalancer.consistentHash) &&
        Objects.equals(this.localityLbSetting, v1alpha3DestinationRuleSpecTrafficPolicyLoadBalancer.localityLbSetting) &&
        Objects.equals(this.simple, v1alpha3DestinationRuleSpecTrafficPolicyLoadBalancer.simple) &&
        Objects.equals(this.warmupDurationSecs, v1alpha3DestinationRuleSpecTrafficPolicyLoadBalancer.warmupDurationSecs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(consistentHash, localityLbSetting, simple, warmupDurationSecs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancer {\n");
    sb.append("    consistentHash: ").append(toIndentedString(consistentHash)).append("\n");
    sb.append("    localityLbSetting: ").append(toIndentedString(localityLbSetting)).append("\n");
    sb.append("    simple: ").append(toIndentedString(simple)).append("\n");
    sb.append("    warmupDurationSecs: ").append(toIndentedString(warmupDurationSecs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

