/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.istio.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * If set then set SO_KEEPALIVE on the socket to enable TCP Keepalives.
 */
@ApiModel(description = "If set then set SO_KEEPALIVE on the socket to enable TCP Keepalives.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-12-20T14:22:47.686Z[Etc/UTC]")
public class V1alpha3DestinationRuleSpecTrafficPolicyConnectionPoolTcpTcpKeepalive {
  public static final String SERIALIZED_NAME_INTERVAL = "interval";
  @SerializedName(SERIALIZED_NAME_INTERVAL)
  private String interval;

  public static final String SERIALIZED_NAME_PROBES = "probes";
  @SerializedName(SERIALIZED_NAME_PROBES)
  private Integer probes;

  public static final String SERIALIZED_NAME_TIME = "time";
  @SerializedName(SERIALIZED_NAME_TIME)
  private String time;


  public V1alpha3DestinationRuleSpecTrafficPolicyConnectionPoolTcpTcpKeepalive interval(String interval) {
    
    this.interval = interval;
    return this;
  }

   /**
   * The time duration between keep-alive probes.
   * @return interval
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The time duration between keep-alive probes.")

  public String getInterval() {
    return interval;
  }


  public void setInterval(String interval) {
    this.interval = interval;
  }


  public V1alpha3DestinationRuleSpecTrafficPolicyConnectionPoolTcpTcpKeepalive probes(Integer probes) {
    
    this.probes = probes;
    return this;
  }

   /**
   * Get probes
   * @return probes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getProbes() {
    return probes;
  }


  public void setProbes(Integer probes) {
    this.probes = probes;
  }


  public V1alpha3DestinationRuleSpecTrafficPolicyConnectionPoolTcpTcpKeepalive time(String time) {
    
    this.time = time;
    return this;
  }

   /**
   * Get time
   * @return time
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTime() {
    return time;
  }


  public void setTime(String time) {
    this.time = time;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha3DestinationRuleSpecTrafficPolicyConnectionPoolTcpTcpKeepalive v1alpha3DestinationRuleSpecTrafficPolicyConnectionPoolTcpTcpKeepalive = (V1alpha3DestinationRuleSpecTrafficPolicyConnectionPoolTcpTcpKeepalive) o;
    return Objects.equals(this.interval, v1alpha3DestinationRuleSpecTrafficPolicyConnectionPoolTcpTcpKeepalive.interval) &&
        Objects.equals(this.probes, v1alpha3DestinationRuleSpecTrafficPolicyConnectionPoolTcpTcpKeepalive.probes) &&
        Objects.equals(this.time, v1alpha3DestinationRuleSpecTrafficPolicyConnectionPoolTcpTcpKeepalive.time);
  }

  @Override
  public int hashCode() {
    return Objects.hash(interval, probes, time);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha3DestinationRuleSpecTrafficPolicyConnectionPoolTcpTcpKeepalive {\n");
    sb.append("    interval: ").append(toIndentedString(interval)).append("\n");
    sb.append("    probes: ").append(toIndentedString(probes)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

