/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.istio.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Hash based on HTTP cookie.
 */
@ApiModel(description = "Hash based on HTTP cookie.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-12-20T14:22:47.686Z[Etc/UTC]")
public class V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHashHttpCookie {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_PATH = "path";
  @SerializedName(SERIALIZED_NAME_PATH)
  private String path;

  public static final String SERIALIZED_NAME_TTL = "ttl";
  @SerializedName(SERIALIZED_NAME_TTL)
  private String ttl;


  public V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHashHttpCookie name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Name of the cookie.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Name of the cookie.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHashHttpCookie path(String path) {
    
    this.path = path;
    return this;
  }

   /**
   * Path to set for the cookie.
   * @return path
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Path to set for the cookie.")

  public String getPath() {
    return path;
  }


  public void setPath(String path) {
    this.path = path;
  }


  public V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHashHttpCookie ttl(String ttl) {
    
    this.ttl = ttl;
    return this;
  }

   /**
   * Lifetime of the cookie.
   * @return ttl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Lifetime of the cookie.")

  public String getTtl() {
    return ttl;
  }


  public void setTtl(String ttl) {
    this.ttl = ttl;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHashHttpCookie v1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHashHttpCookie = (V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHashHttpCookie) o;
    return Objects.equals(this.name, v1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHashHttpCookie.name) &&
        Objects.equals(this.path, v1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHashHttpCookie.path) &&
        Objects.equals(this.ttl, v1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHashHttpCookie.ttl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, path, ttl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHashHttpCookie {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    ttl: ").append(toIndentedString(ttl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

