/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.istio.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.istio.models.V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHashHttpCookie;
import io.istio.models.V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHashMaglev;
import io.istio.models.V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHashRingHash;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHash
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-12-20T14:22:47.686Z[Etc/UTC]")
public class V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHash {
  public static final String SERIALIZED_NAME_HTTP_COOKIE = "httpCookie";
  @SerializedName(SERIALIZED_NAME_HTTP_COOKIE)
  private V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHashHttpCookie httpCookie;

  public static final String SERIALIZED_NAME_HTTP_HEADER_NAME = "httpHeaderName";
  @SerializedName(SERIALIZED_NAME_HTTP_HEADER_NAME)
  private String httpHeaderName;

  public static final String SERIALIZED_NAME_HTTP_QUERY_PARAMETER_NAME = "httpQueryParameterName";
  @SerializedName(SERIALIZED_NAME_HTTP_QUERY_PARAMETER_NAME)
  private String httpQueryParameterName;

  public static final String SERIALIZED_NAME_MAGLEV = "maglev";
  @SerializedName(SERIALIZED_NAME_MAGLEV)
  private V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHashMaglev maglev;

  public static final String SERIALIZED_NAME_MINIMUM_RING_SIZE = "minimumRingSize";
  @SerializedName(SERIALIZED_NAME_MINIMUM_RING_SIZE)
  private Integer minimumRingSize;

  public static final String SERIALIZED_NAME_RING_HASH = "ringHash";
  @SerializedName(SERIALIZED_NAME_RING_HASH)
  private V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHashRingHash ringHash;

  public static final String SERIALIZED_NAME_USE_SOURCE_IP = "useSourceIp";
  @SerializedName(SERIALIZED_NAME_USE_SOURCE_IP)
  private Boolean useSourceIp;


  public V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHash httpCookie(V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHashHttpCookie httpCookie) {
    
    this.httpCookie = httpCookie;
    return this;
  }

   /**
   * Get httpCookie
   * @return httpCookie
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHashHttpCookie getHttpCookie() {
    return httpCookie;
  }


  public void setHttpCookie(V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHashHttpCookie httpCookie) {
    this.httpCookie = httpCookie;
  }


  public V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHash httpHeaderName(String httpHeaderName) {
    
    this.httpHeaderName = httpHeaderName;
    return this;
  }

   /**
   * Hash based on a specific HTTP header.
   * @return httpHeaderName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Hash based on a specific HTTP header.")

  public String getHttpHeaderName() {
    return httpHeaderName;
  }


  public void setHttpHeaderName(String httpHeaderName) {
    this.httpHeaderName = httpHeaderName;
  }


  public V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHash httpQueryParameterName(String httpQueryParameterName) {
    
    this.httpQueryParameterName = httpQueryParameterName;
    return this;
  }

   /**
   * Hash based on a specific HTTP query parameter.
   * @return httpQueryParameterName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Hash based on a specific HTTP query parameter.")

  public String getHttpQueryParameterName() {
    return httpQueryParameterName;
  }


  public void setHttpQueryParameterName(String httpQueryParameterName) {
    this.httpQueryParameterName = httpQueryParameterName;
  }


  public V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHash maglev(V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHashMaglev maglev) {
    
    this.maglev = maglev;
    return this;
  }

   /**
   * Get maglev
   * @return maglev
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHashMaglev getMaglev() {
    return maglev;
  }


  public void setMaglev(V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHashMaglev maglev) {
    this.maglev = maglev;
  }


  public V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHash minimumRingSize(Integer minimumRingSize) {
    
    this.minimumRingSize = minimumRingSize;
    return this;
  }

   /**
   * Deprecated.
   * @return minimumRingSize
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Deprecated.")

  public Integer getMinimumRingSize() {
    return minimumRingSize;
  }


  public void setMinimumRingSize(Integer minimumRingSize) {
    this.minimumRingSize = minimumRingSize;
  }


  public V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHash ringHash(V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHashRingHash ringHash) {
    
    this.ringHash = ringHash;
    return this;
  }

   /**
   * Get ringHash
   * @return ringHash
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHashRingHash getRingHash() {
    return ringHash;
  }


  public void setRingHash(V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHashRingHash ringHash) {
    this.ringHash = ringHash;
  }


  public V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHash useSourceIp(Boolean useSourceIp) {
    
    this.useSourceIp = useSourceIp;
    return this;
  }

   /**
   * Hash based on the source IP address.
   * @return useSourceIp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Hash based on the source IP address.")

  public Boolean getUseSourceIp() {
    return useSourceIp;
  }


  public void setUseSourceIp(Boolean useSourceIp) {
    this.useSourceIp = useSourceIp;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHash v1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHash = (V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHash) o;
    return Objects.equals(this.httpCookie, v1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHash.httpCookie) &&
        Objects.equals(this.httpHeaderName, v1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHash.httpHeaderName) &&
        Objects.equals(this.httpQueryParameterName, v1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHash.httpQueryParameterName) &&
        Objects.equals(this.maglev, v1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHash.maglev) &&
        Objects.equals(this.minimumRingSize, v1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHash.minimumRingSize) &&
        Objects.equals(this.ringHash, v1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHash.ringHash) &&
        Objects.equals(this.useSourceIp, v1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHash.useSourceIp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(httpCookie, httpHeaderName, httpQueryParameterName, maglev, minimumRingSize, ringHash, useSourceIp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha3DestinationRuleSpecTrafficPolicyLoadBalancerConsistentHash {\n");
    sb.append("    httpCookie: ").append(toIndentedString(httpCookie)).append("\n");
    sb.append("    httpHeaderName: ").append(toIndentedString(httpHeaderName)).append("\n");
    sb.append("    httpQueryParameterName: ").append(toIndentedString(httpQueryParameterName)).append("\n");
    sb.append("    maglev: ").append(toIndentedString(maglev)).append("\n");
    sb.append("    minimumRingSize: ").append(toIndentedString(minimumRingSize)).append("\n");
    sb.append("    ringHash: ").append(toIndentedString(ringHash)).append("\n");
    sb.append("    useSourceIp: ").append(toIndentedString(useSourceIp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

